use engine_core::color::Color;

#[derive(Debug, Clone)]
pub struct ObjRenderParams {
    pub scale: f32,
    pub yaw_deg: f32,
    pub pitch_deg: f32,
    pub roll_deg: f32,
    pub rotation_x: f32,
    pub rotation_y: f32,
    pub rotation_z: f32,
    pub rotate_y_deg_per_sec: f32,
    pub camera_distance: f32,
    pub fov_degrees: f32,
    pub near_clip: f32,
    pub light_direction_x: f32,
    pub light_direction_y: f32,
    pub light_direction_z: f32,
    pub light_2_direction_x: f32,
    pub light_2_direction_y: f32,
    pub light_2_direction_z: f32,
    pub light_2_intensity: f32,
    pub light_point_x: f32,
    pub light_point_y: f32,
    pub light_point_z: f32,
    pub light_point_intensity: f32,
    pub light_point_colour: Option<Color>,
    pub light_point_flicker_depth: f32,
    pub light_point_flicker_hz: f32,
    pub light_point_orbit_hz: f32,
    pub light_point_snap_hz: f32,
    pub light_point_2_x: f32,
    pub light_point_2_y: f32,
    pub light_point_2_z: f32,
    pub light_point_2_intensity: f32,
    pub light_point_2_colour: Option<Color>,
    pub light_point_2_flicker_depth: f32,
    pub light_point_2_flicker_hz: f32,
    pub light_point_2_orbit_hz: f32,
    pub light_point_2_snap_hz: f32,
    pub cel_levels: u8,
    pub shadow_colour: Option<Color>,
    pub midtone_colour: Option<Color>,
    pub highlight_colour: Option<Color>,
    pub tone_mix: f32,
    pub scene_elapsed_ms: u64,
    pub camera_pan_x: f32,
    pub camera_pan_y: f32,
    pub camera_look_yaw: f32,
    pub camera_look_pitch: f32,
    pub object_translate_x: f32,
    pub object_translate_y: f32,
    pub object_translate_z: f32,
    pub clip_y_min: f32,
    pub clip_y_max: f32,
    pub camera_world_x: f32,
    pub camera_world_y: f32,
    pub camera_world_z: f32,
    pub view_right_x: f32,
    pub view_right_y: f32,
    pub view_right_z: f32,
    pub view_up_x: f32,
    pub view_up_y: f32,
    pub view_up_z: f32,
    pub view_forward_x: f32,
    pub view_forward_y: f32,
    pub view_forward_z: f32,
    pub unlit: bool,
    pub ambient: f32,
    pub light_point_falloff: f32,
    pub light_point_2_falloff: f32,
    pub smooth_shading: bool,
    pub latitude_bands: u8,
    pub latitude_band_depth: f32,
    pub terrain_color: Option<[u8; 3]>,
    pub terrain_threshold: f32,
    pub terrain_noise_scale: f32,
    pub terrain_noise_octaves: u8,
    pub marble_depth: f32,
    pub terrain_relief: f32,
    pub noise_seed: f32,
    pub warp_strength: f32,
    pub warp_octaves: u8,
    pub noise_lacunarity: f32,
    pub noise_persistence: f32,
    pub normal_perturb_strength: f32,
    pub ocean_specular: f32,
    pub crater_density: f32,
    pub crater_rim_height: f32,
    pub snow_line_altitude: f32,
    pub terrain_displacement: f32,
    pub below_threshold_transparent: bool,
    pub cloud_alpha_softness: f32,
    pub polar_ice_color: Option<[u8; 3]>,
    pub polar_ice_start: f32,
    pub polar_ice_end: f32,
    pub desert_color: Option<[u8; 3]>,
    pub desert_strength: f32,
    pub atmo_color: Option<[u8; 3]>,
    pub atmo_height: f32,
    pub atmo_density: f32,
    pub atmo_strength: f32,
    pub atmo_rayleigh_amount: f32,
    pub atmo_rayleigh_color: Option<[u8; 3]>,
    pub atmo_rayleigh_falloff: f32,
    pub atmo_haze_amount: f32,
    pub atmo_haze_color: Option<[u8; 3]>,
    pub atmo_haze_falloff: f32,
    pub atmo_absorption_amount: f32,
    pub atmo_absorption_color: Option<[u8; 3]>,
    pub atmo_absorption_height: f32,
    pub atmo_absorption_width: f32,
    pub atmo_forward_scatter: f32,
    pub atmo_limb_boost: f32,
    pub atmo_terminator_softness: f32,
    pub atmo_night_glow: f32,
    pub atmo_night_glow_color: Option<[u8; 3]>,
    pub atmo_rim_power: f32,
    pub atmo_haze_strength: f32,
    pub atmo_haze_power: f32,
    pub atmo_veil_strength: f32,
    pub atmo_veil_power: f32,
    pub atmo_halo_strength: f32,
    pub atmo_halo_width: f32,
    pub atmo_halo_power: f32,
    pub ocean_noise_scale: f32,
    pub ocean_color_rgb: Option<[u8; 3]>,
    pub night_light_color: Option<[u8; 3]>,
    pub night_light_threshold: f32,
    pub night_light_intensity: f32,
    pub heightmap: Option<std::sync::Arc<Vec<f32>>>,
    pub heightmap_w: u32,
    pub heightmap_h: u32,
    pub heightmap_blend: f32,
    pub depth_sort_faces: bool,
}
