# yaml-language-server: $schema=../../../../schemas/scene.schema.yaml
id: intro-text
title: intro-text.test
cutscene: true
bg: black
stages:
  on_enter:
    steps:
      - pause: 24000ms
  on_idle:
    trigger: none
    steps:
      - pause: 1ms
layers:
  - name: text
    sprites:
      - type: text
        id: verse-1-text
        content: "From mother's love is the son estranged"
        at: cc
        font: "Abril Fatface:terminal-pixels"
        wrap: word
        max-width: 140
        fg: white
        bg: black
        glow:
          colour: "#5f7cff"
          radius: 1
        appear_at_ms: 0
        disappear_at_ms: 4000
        stages:
          on_enter:
            steps:
              - effects:
                  - name: fade-in
                    duration: 900
                    params:
                      easing: ease-out
              - duration: 2200
              - effects:
                  - name: fade-out
                    duration: 900
                    params:
                      easing: ease-in
      - type: text
        id: verse-2-text
        content: "Married his own, his precious gain"
        at: cc
        font: "Abril Fatface:terminal-pixels"
        wrap: word
        max-width: 140
        fg: white
        bg: black
        glow:
          colour: "#5f7cff"
          radius: 1
        appear_at_ms: 4000
        disappear_at_ms: 8000
        stages:
          on_enter:
            steps:
              - effects:
                  - name: fade-in
                    duration: 900
                    params:
                      easing: ease-out
              - duration: 2200
              - effects:
                  - name: fade-out
                    duration: 900
                    params:
                      easing: ease-in
      - type: text
        id: verse-3-text
        content: "The earth will shake, in two will break"
        at: cc
        font: "Abril Fatface:terminal-pixels"
        wrap: word
        max-width: 140
        fg: white
        bg: black
        glow:
          colour: "#5f7cff"
          radius: 1
        appear_at_ms: 8000
        disappear_at_ms: 12000
        stages:
          on_enter:
            steps:
              - effects:
                  - name: fade-in
                    duration: 900
                    params:
                      easing: ease-out
              - duration: 2200
              - effects:
                  - name: fade-out
                    duration: 900
                    params:
                      easing: ease-in
      - type: text
        id: verse-4-text
        content: "And death all round will be your dowry"
        at: cc
        font: "Abril Fatface:terminal-pixels"
        wrap: word
        max-width: 140
        fg: white
        bg: black
        glow:
          colour: "#5f7cff"
          radius: 1
        appear_at_ms: 12000
        disappear_at_ms: 16000
        stages:
          on_enter:
            steps:
              - effects:
                  - name: fade-in
                    duration: 900
                    params:
                      easing: ease-out
              - duration: 2200
              - effects:
                  - name: fade-out
                    duration: 900
                    params:
                      easing: ease-in
      - type: text
        id: verse-5-text
        content: "Ah, ah, people of the earth"
        at: cc
        font: "Abril Fatface:terminal-pixels"
        wrap: word
        max-width: 140
        fg: white
        bg: black
        glow:
          colour: "#5f7cff"
          radius: 1
        appear_at_ms: 16000
        disappear_at_ms: 20000
        stages:
          on_enter:
            steps:
              - effects:
                  - name: fade-in
                    duration: 900
                    params:
                      easing: ease-out
              - duration: 2200
              - effects:
                  - name: fade-out
                    duration: 900
                    params:
                      easing: ease-in
      - type: text
        id: verse-6-text
        content: "Listen to the warning, the seer he said"
        at: cc
        font: "Abril Fatface:terminal-pixels"
        wrap: word
        max-width: 140
        fg: white
        bg: black
        glow:
          colour: "#5f7cff"
          radius: 1
        appear_at_ms: 20000
        disappear_at_ms: 24000
        stages:
          on_enter:
            steps:
              - effects:
                  - name: fade-in
                    duration: 900
                    params:
                      easing: ease-out
              - duration: 2200
              - effects:
                  - name: fade-out
                    duration: 900
                    params:
                      easing: ease-in
