//! High-level editor commands dispatched from key events.

/// High-level action the application should perform in response to a key event.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Command {
    Quit,
    Back,
    Up,
    Down,
    Left,
    Right,
    Enter,
    OpenProject,
    OpenSchemaPicker,
    PruneRecents,
    TogglePreview,
    CloseProject,
    NextPane,
    PrevPane,
    EnterFile,
    ExitEditor,
    ToggleSidebar,
    ToggleEffectsPreview,
    SceneFullscreenHoldStart,
    SceneFullscreenHoldEnd,
    ToggleSceneFullscreen,
    ToggleSceneLayer,
    SelectPanel1,
    SelectPanel2,
    SelectPanel3,
    SelectPanel4,
    NextCodeTab,
    PrevCodeTab,
    Noop,
}
