# yaml-language-server: $schema=../../schemas/scenes.yaml
id: 04.intro.difficulty-select
title: 04 Intro Difficulty Select
bg: black
prerender: true
layers:
  - ref: main
stages:
  on_enter:
    steps:
      - { effects: [{ name: fade-in, duration: 280, params: { easing: ease-out } }] }
  on_idle:
    trigger: any-key
    looping: true
    steps:
      - { pause: 1200ms }
  on_leave:
    steps:
      - { pause: 600ms }
      - { effects: [{ name: fade-out, duration: 220, params: { easing: ease-in } }] }
next: 05.intro.cpu-on
menu-options:
  - { key: "1", label: "MOUSE ENJOYER", to: 05.intro.cpu-on }
  - { key: "2", label: "SCRIPT KIDDIE", to: 05.intro.cpu-on }
  - { key: "3", label: "I CAN EXIT VIM", to: 05.intro.cpu-on }
  - { key: "4", label: "DVORAK", to: 05.intro.cpu-on }
  - { key: "5", label: "SU", to: 05.intro.cpu-on }
