//! Static field-metadata tables for every authoring target (scene, layer, sprite, object).

use crate::authoring::metadata::{FieldMetadata, Requirement, TargetKind, ValueKind, ValueSource};

const LIT_ONLY: &[ValueSource] = &[ValueSource::Literal];
const LIT_EXPR: &[ValueSource] = &[ValueSource::Literal, ValueSource::Expression];
const LIT_EXPR_BIND: &[ValueSource] = &[
    ValueSource::Literal,
    ValueSource::Expression,
    ValueSource::Binding,
];
const LIT_EXPR_BIND_ANIM: &[ValueSource] = &[
    ValueSource::Literal,
    ValueSource::Expression,
    ValueSource::Binding,
    ValueSource::Animation,
];

const SPRITE_TYPE_OPTIONS: &[&str] = &["text", "image", "obj", "grid", "flex"];
const LOGIC_TYPE_OPTIONS: &[&str] = &["native", "graph", "script"];
const RENDERED_MODE_OPTIONS: &[&str] = &["cell", "halfblock", "quadblock", "braille"];
const ALIGN_X_OPTIONS: &[&str] = &["left", "center", "right"];
const ALIGN_Y_OPTIONS: &[&str] = &["top", "center", "bottom"];
const AT_OPTIONS: &[&str] = &["cc", "ct", "cb", "lc", "rc", "lt", "lb", "rt", "rb"];
const SURFACE_MODE_OPTIONS: &[&str] = &["material", "wireframe"];
const FLEX_DIRECTION_OPTIONS: &[&str] = &["column", "row"];
const FORCE_FONT_MODE_OPTIONS: &[&str] = &[
    "ascii", "raster", "terminal-pixels",
    "1", "2", "3", "tiny", "standard", "large", "half", "quad", "braille",
];

/// Field metadata for scene-level properties.
pub static SCENE_FIELDS: &[FieldMetadata] = &[
    FieldMetadata {
        target: TargetKind::Scene,
        name: "id",
        value_kind: ValueKind::Text,
        requirement: Requirement::Required,
        description: "Unique scene identifier.",
        default_text: None, default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: None,
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Scene,
        name: "title",
        value_kind: ValueKind::Text,
        requirement: Requirement::Required,
        description: "Human-readable scene title.",
        default_text: None, default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: None,
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Scene,
        name: "bg",
        value_kind: ValueKind::Colour,
        requirement: Requirement::Optional,
        description: "Scene background colour (alias of bg_colour).",
        default_text: Some("black"), default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: None,
        sources: LIT_EXPR_BIND,
    },
    FieldMetadata {
        target: TargetKind::Scene,
        name: "bg_colour",
        value_kind: ValueKind::Colour,
        requirement: Requirement::Optional,
        description: "Terminal background colour filling the entire buffer on scene load.",
        default_text: Some("black"), default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: None,
        sources: LIT_EXPR_BIND,
    },
    FieldMetadata {
        target: TargetKind::Scene,
        name: "cutscene",
        value_kind: ValueKind::Boolean,
        requirement: Requirement::Optional,
        description: "Whether this scene is a non-interactive cutscene.",
        default_text: Some("false"), default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: None,
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Scene,
        name: "target-fps",
        value_kind: ValueKind::Integer,
        requirement: Requirement::Optional,
        description: "Optional scene-level FPS cap override.",
        default_text: None, default_number: None, enum_options: None,
        min: Some(1.0), max: Some(240.0), step: Some(1.0), unit: Some("fps"),
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Scene,
        name: "target_fps",
        value_kind: ValueKind::Integer,
        requirement: Requirement::Optional,
        description: "Alias of target-fps.",
        default_text: None, default_number: None, enum_options: None,
        min: Some(1.0), max: Some(240.0), step: Some(1.0), unit: Some("fps"),
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Scene,
        name: "rendered-mode",
        value_kind: ValueKind::Select,
        requirement: Requirement::Optional,
        description: "Optional scene-level renderer packing mode override.",
        default_text: None, default_number: None, enum_options: Some(RENDERED_MODE_OPTIONS),
        min: None, max: None, step: None, unit: None,
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Scene,
        name: "virtual-size-override",
        value_kind: ValueKind::Text,
        requirement: Requirement::Optional,
        description: "Optional virtual canvas override in WIDTHxHEIGHT form (e.g. 320x240).",
        default_text: None, default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: None,
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Scene,
        name: "next",
        value_kind: ValueKind::Text,
        requirement: Requirement::Optional,
        description: "Scene id to transition to when on_leave completes.",
        default_text: None, default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: None,
        sources: LIT_ONLY,
    },
];

/// Field metadata for layer-level properties.
pub static LAYER_FIELDS: &[FieldMetadata] = &[
    FieldMetadata {
        target: TargetKind::Layer,
        name: "name",
        value_kind: ValueKind::Text,
        requirement: Requirement::Required,
        description: "Layer identifier.",
        default_text: None, default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: None,
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Layer,
        name: "z_index",
        value_kind: ValueKind::Integer,
        requirement: Requirement::Optional,
        description: "Layer render order. Higher z_index renders on top.",
        default_text: None, default_number: Some(0.0), enum_options: None,
        min: None, max: None, step: Some(1.0), unit: None,
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Layer,
        name: "visible",
        value_kind: ValueKind::Boolean,
        requirement: Requirement::Optional,
        description: "Whether this layer is composited onto the scene framebuffer.",
        default_text: Some("true"), default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: None,
        sources: LIT_ONLY,
    },
];

/// Field metadata for sprite-level properties.
pub static SPRITE_FIELDS: &[FieldMetadata] = &[
    // ── Core ────────────────────────────────────────────────────────────────
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "type",
        value_kind: ValueKind::Select,
        requirement: Requirement::Required,
        description: "Sprite kind: text, image, obj (3-D mesh), grid, or flex.",
        default_text: None, default_number: None, enum_options: Some(SPRITE_TYPE_OPTIONS),
        min: None, max: None, step: None, unit: None,
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "content",
        value_kind: ValueKind::Text,
        requirement: Requirement::RequiredIf { field: "type", equals: "text" },
        description: "Text content to render (required for type=text).",
        default_text: None, default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: None,
        sources: &[ValueSource::Literal, ValueSource::Binding, ValueSource::Expression],
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "source",
        value_kind: ValueKind::Text,
        requirement: Requirement::RequiredIf { field: "type", equals: "image" },
        description: "Asset path (required for type=image/obj).",
        default_text: None, default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: None,
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "id",
        value_kind: ValueKind::Text,
        requirement: Requirement::Optional,
        description: "Optional stable sprite identifier for script-side hooks.",
        default_text: None, default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: None,
        sources: LIT_ONLY,
    },
    // ── Position / layout ───────────────────────────────────────────────────
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "x",
        value_kind: ValueKind::Text,
        requirement: Requirement::Optional,
        description: "Signed horizontal offset (integer or expression, e.g. oscillate(-2,2,1800ms)).",
        default_text: Some("0"), default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: Some("cells"),
        sources: LIT_EXPR_BIND_ANIM,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "y",
        value_kind: ValueKind::Text,
        requirement: Requirement::Optional,
        description: "Signed vertical offset (integer or expression).",
        default_text: Some("0"), default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: Some("cells"),
        sources: LIT_EXPR_BIND_ANIM,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "z_index",
        value_kind: ValueKind::Integer,
        requirement: Requirement::Optional,
        description: "Render order within the layer. Higher z_index renders on top.",
        default_text: None, default_number: Some(0.0), enum_options: None,
        min: None, max: None, step: Some(1.0), unit: None,
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "align_x",
        value_kind: ValueKind::Select,
        requirement: Requirement::Optional,
        description: "Horizontal alignment anchor in scene space.",
        default_text: None, default_number: None, enum_options: Some(ALIGN_X_OPTIONS),
        min: None, max: None, step: None, unit: None,
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "align_y",
        value_kind: ValueKind::Select,
        requirement: Requirement::Optional,
        description: "Vertical alignment anchor in scene space.",
        default_text: None, default_number: None, enum_options: Some(ALIGN_Y_OPTIONS),
        min: None, max: None, step: None, unit: None,
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "at",
        value_kind: ValueKind::Select,
        requirement: Requirement::Optional,
        description: "Alignment shorthand for align_x+align_y (e.g. cc, lt, rb).",
        default_text: None, default_number: None, enum_options: Some(AT_OPTIONS),
        min: None, max: None, step: None, unit: None,
        sources: LIT_ONLY,
    },
    // ── Size ────────────────────────────────────────────────────────────────
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "width",
        value_kind: ValueKind::Integer,
        requirement: Requirement::Optional,
        description: "Target sprite width in terminal cells.",
        default_text: None, default_number: None, enum_options: None,
        min: Some(1.0), max: Some(65535.0), step: Some(1.0), unit: Some("cells"),
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "height",
        value_kind: ValueKind::Integer,
        requirement: Requirement::Optional,
        description: "Target sprite height in terminal cells.",
        default_text: None, default_number: None, enum_options: None,
        min: Some(1.0), max: Some(65535.0), step: Some(1.0), unit: Some("cells"),
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "size",
        value_kind: ValueKind::Integer,
        requirement: Requirement::Optional,
        description: "Sprite size preset: 1=small, 2=medium, 3=large.",
        default_text: None, default_number: None, enum_options: None,
        min: Some(1.0), max: Some(3.0), step: Some(1.0), unit: None,
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "font",
        value_kind: ValueKind::Text,
        requirement: Requirement::Optional,
        description: "Font for rasterized rendering (e.g. generic:2). Omit for native terminal text.",
        default_text: None, default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: None,
        sources: LIT_ONLY,
    },
    // ── Colour ──────────────────────────────────────────────────────────────
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "fg_colour",
        value_kind: ValueKind::Colour,
        requirement: Requirement::Optional,
        description: "Base foreground (text/glyph) colour.",
        default_text: None, default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: None,
        sources: LIT_EXPR_BIND,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "fg",
        value_kind: ValueKind::Colour,
        requirement: Requirement::Optional,
        description: "Alias of fg_colour.",
        default_text: None, default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: None,
        sources: LIT_EXPR_BIND,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "bg_colour",
        value_kind: ValueKind::Colour,
        requirement: Requirement::Optional,
        description: "Background colour behind the sprite.",
        default_text: None, default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: None,
        sources: LIT_EXPR_BIND,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "bg",
        value_kind: ValueKind::Colour,
        requirement: Requirement::Optional,
        description: "Alias of bg_colour.",
        default_text: None, default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: None,
        sources: LIT_EXPR_BIND,
    },
    // ── Timing / visibility ─────────────────────────────────────────────────
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "appear_at_ms",
        value_kind: ValueKind::Integer,
        requirement: Requirement::Optional,
        description: "Delay from scene start (ms) before this sprite becomes visible.",
        default_text: None, default_number: None, enum_options: None,
        min: Some(0.0), max: None, step: Some(1.0), unit: Some("ms"),
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "disappear_at_ms",
        value_kind: ValueKind::Integer,
        requirement: Requirement::Optional,
        description: "Absolute scene time (ms) after which this sprite is hidden.",
        default_text: None, default_number: None, enum_options: None,
        min: Some(0.0), max: None, step: Some(1.0), unit: Some("ms"),
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "reveal_ms",
        value_kind: ValueKind::Integer,
        requirement: Requirement::Optional,
        description: "Optional reveal duration (ms) — content appears character by character.",
        default_text: None, default_number: None, enum_options: None,
        min: Some(0.0), max: None, step: Some(1.0), unit: Some("ms"),
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "hide_on_leave",
        value_kind: ValueKind::Boolean,
        requirement: Requirement::Optional,
        description: "When true, sprite is hidden once the scene enters on_leave.",
        default_text: Some("false"), default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: None,
        sources: LIT_ONLY,
    },
    // ── Renderer overrides ──────────────────────────────────────────────────
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "force-renderer-mode",
        value_kind: ValueKind::Select,
        requirement: Requirement::Optional,
        description: "Optional per-sprite renderer mode override.",
        default_text: None, default_number: None, enum_options: Some(RENDERED_MODE_OPTIONS),
        min: None, max: None, step: None, unit: None,
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "force-font-mode",
        value_kind: ValueKind::Select,
        requirement: Requirement::Optional,
        description: "Optional per-sprite font mode override.",
        default_text: None, default_number: None, enum_options: Some(FORCE_FONT_MODE_OPTIONS),
        min: None, max: None, step: None, unit: None,
        sources: LIT_ONLY,
    },
    // ── Grid child layout ────────────────────────────────────────────────────
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "grid-row",
        value_kind: ValueKind::Integer,
        requirement: Requirement::Optional,
        description: "Grid row index (1-based) when this sprite is a child of a grid container.",
        default_text: None, default_number: Some(1.0), enum_options: None,
        min: Some(1.0), max: None, step: Some(1.0), unit: None,
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "grid-col",
        value_kind: ValueKind::Integer,
        requirement: Requirement::Optional,
        description: "Grid column index (1-based) when this sprite is a child of a grid container.",
        default_text: None, default_number: Some(1.0), enum_options: None,
        min: Some(1.0), max: None, step: Some(1.0), unit: None,
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "row-span",
        value_kind: ValueKind::Integer,
        requirement: Requirement::Optional,
        description: "Number of grid rows this sprite spans.",
        default_text: None, default_number: Some(1.0), enum_options: None,
        min: Some(1.0), max: None, step: Some(1.0), unit: None,
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "col-span",
        value_kind: ValueKind::Integer,
        requirement: Requirement::Optional,
        description: "Number of grid columns this sprite spans.",
        default_text: None, default_number: Some(1.0), enum_options: None,
        min: Some(1.0), max: None, step: Some(1.0), unit: None,
        sources: LIT_ONLY,
    },
    // ── Grid/flex container ──────────────────────────────────────────────────
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "gap-x",
        value_kind: ValueKind::Integer,
        requirement: Requirement::Optional,
        description: "Horizontal gap between grid columns in cells.",
        default_text: None, default_number: Some(0.0), enum_options: None,
        min: Some(0.0), max: None, step: Some(1.0), unit: Some("cells"),
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "gap-y",
        value_kind: ValueKind::Integer,
        requirement: Requirement::Optional,
        description: "Vertical gap between grid rows in cells.",
        default_text: None, default_number: Some(0.0), enum_options: None,
        min: Some(0.0), max: None, step: Some(1.0), unit: Some("cells"),
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "gap",
        value_kind: ValueKind::Integer,
        requirement: Requirement::Optional,
        description: "Gap between flex children on the main axis in cells (type=flex).",
        default_text: None, default_number: Some(0.0), enum_options: None,
        min: Some(0.0), max: None, step: Some(1.0), unit: Some("cells"),
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "direction",
        value_kind: ValueKind::Select,
        requirement: Requirement::Optional,
        description: "Flex direction for type=flex: column stacks vertically, row horizontally.",
        default_text: Some("column"), default_number: None, enum_options: Some(FLEX_DIRECTION_OPTIONS),
        min: None, max: None, step: None, unit: None,
        sources: LIT_ONLY,
    },
    // ── 3-D (obj) ────────────────────────────────────────────────────────────
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "scale",
        value_kind: ValueKind::Number,
        requirement: Requirement::Optional,
        description: "Uniform mesh scale multiplier for type=obj.",
        default_text: None, default_number: None, enum_options: None,
        min: Some(0.0001), max: None, step: None, unit: None,
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "yaw-deg",
        value_kind: ValueKind::Number,
        requirement: Requirement::Optional,
        description: "Static yaw (Y-axis) rotation in degrees for type=obj.",
        default_text: None, default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: Some("deg"),
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "pitch-deg",
        value_kind: ValueKind::Number,
        requirement: Requirement::Optional,
        description: "Static pitch (X-axis) rotation in degrees for type=obj.",
        default_text: None, default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: Some("deg"),
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "roll-deg",
        value_kind: ValueKind::Number,
        requirement: Requirement::Optional,
        description: "Static roll (Z-axis) rotation in degrees for type=obj.",
        default_text: None, default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: Some("deg"),
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "rotation-x",
        value_kind: ValueKind::Number,
        requirement: Requirement::Optional,
        description: "Static initial X-axis rotation in degrees for type=obj.",
        default_text: None, default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: Some("deg"),
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "rotation-y",
        value_kind: ValueKind::Text,
        requirement: Requirement::Optional,
        description: "Static initial Y-axis rotation (number or expression like animate(180deg,540deg,12s,loop)).",
        default_text: None, default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: Some("deg"),
        sources: LIT_EXPR,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "rotation-z",
        value_kind: ValueKind::Number,
        requirement: Requirement::Optional,
        description: "Static initial Z-axis rotation in degrees for type=obj.",
        default_text: None, default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: Some("deg"),
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "rotate-y-deg-per-sec",
        value_kind: ValueKind::Number,
        requirement: Requirement::Optional,
        description: "Continuous Y-axis rotation speed in degrees per second for type=obj.",
        default_text: None, default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: Some("deg/s"),
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "camera-distance",
        value_kind: ValueKind::Number,
        requirement: Requirement::Optional,
        description: "Camera distance from mesh center for perspective projection (type=obj).",
        default_text: None, default_number: None, enum_options: None,
        min: Some(0.01), max: None, step: None, unit: None,
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "fov-degrees",
        value_kind: ValueKind::Number,
        requirement: Requirement::Optional,
        description: "Perspective camera FOV in degrees for type=obj.",
        default_text: None, default_number: None, enum_options: None,
        min: Some(1.0), max: Some(179.0), step: None, unit: Some("deg"),
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "near-clip",
        value_kind: ValueKind::Number,
        requirement: Requirement::Optional,
        description: "Near clipping plane distance in camera space for type=obj.",
        default_text: None, default_number: None, enum_options: None,
        min: Some(0.000001), max: None, step: None, unit: None,
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "draw-char",
        value_kind: ValueKind::Text,
        requirement: Requirement::Optional,
        description: "Single glyph used to draw wireframe edges for type=obj.",
        default_text: None, default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: None,
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "surface-mode",
        value_kind: ValueKind::Select,
        requirement: Requirement::Optional,
        description: "Surface rendering style for type=obj: material fills faces, wireframe draws edges.",
        default_text: None, default_number: None, enum_options: Some(SURFACE_MODE_OPTIONS),
        min: None, max: None, step: None, unit: None,
        sources: LIT_ONLY,
    },
    // ── Grid required fields ─────────────────────────────────────────────────
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "columns",
        value_kind: ValueKind::SelectList,
        requirement: Requirement::RequiredIf { field: "type", equals: "grid" },
        description: "Grid column track definitions (\"auto\", \"<n>fr\", or \"<n>\" fixed cells).",
        default_text: None, default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: None,
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Sprite,
        name: "rows",
        value_kind: ValueKind::SelectList,
        requirement: Requirement::RequiredIf { field: "type", equals: "grid" },
        description: "Grid row track definitions (\"auto\", \"<n>fr\", or \"<n>\" fixed cells).",
        default_text: None, default_number: None, enum_options: None,
        min: None, max: None, step: None, unit: None,
        sources: LIT_ONLY,
    },
];

/// Field metadata for object/prefab-level properties.
pub static OBJECT_FIELDS: &[FieldMetadata] = &[
    FieldMetadata {
        target: TargetKind::Object,
        name: "name",
        value_kind: ValueKind::Text,
        requirement: Requirement::Required,
        description: "Object/prefab identifier.",
        default_text: None,
        default_number: None,
        enum_options: None,
        min: None,
        max: None,
        step: None,
        unit: None,
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Object,
        name: "exports",
        value_kind: ValueKind::Text,
        requirement: Requirement::Optional,
        description: "Optional default substitution values.",
        default_text: None,
        default_number: None,
        enum_options: None,
        min: None,
        max: None,
        step: None,
        unit: None,
        sources: LIT_EXPR_BIND_ANIM,
    },
    FieldMetadata {
        target: TargetKind::Object,
        name: "logic.type",
        value_kind: ValueKind::Select,
        requirement: Requirement::Optional,
        description: "Object logic backend type.",
        default_text: Some("native"),
        default_number: None,
        enum_options: Some(LOGIC_TYPE_OPTIONS),
        min: None,
        max: None,
        step: None,
        unit: None,
        sources: LIT_ONLY,
    },
    FieldMetadata {
        target: TargetKind::Object,
        name: "effects",
        value_kind: ValueKind::Text,
        requirement: Requirement::Optional,
        description: "Optional object-level effects (if present in object authored shape).",
        default_text: None,
        default_number: None,
        enum_options: None,
        min: None,
        max: None,
        step: None,
        unit: None,
        sources: LIT_ONLY,
    },
];

#[cfg(test)]
mod tests {
    use super::{OBJECT_FIELDS, SPRITE_FIELDS};
    use crate::authoring::metadata::Requirement;

    #[test]
    fn sprite_content_is_required_for_text_type() {
        let field = SPRITE_FIELDS
            .iter()
            .find(|f| f.name == "content")
            .expect("content metadata");
        assert_eq!(
            field.requirement,
            Requirement::RequiredIf {
                field: "type",
                equals: "text"
            }
        );
    }

    #[test]
    fn object_effects_are_optional() {
        let field = OBJECT_FIELDS
            .iter()
            .find(|f| f.name == "effects")
            .expect("effects metadata");
        assert_eq!(field.requirement, Requirement::Optional);
    }
}
