# yaml-language-server: $schema=../../schemas/scenes.yaml
id: playground-exit
title: Exit
virtual-size-override: 640x360
bg: black
layers:
  - ref: main
stages:
  on_enter:
    steps:
      - pause: 1ms
next: null

