# yaml-language-server: $schema=../../../schemas/scene.schema.yaml
id: playground-fps-showcase-20
title: FPS Showcase 3D 20
cutscene: true
target-fps: 20
bg: black
rendered-mode: quadblock
stages:
  on_idle:
    trigger: timeout
    steps:
      - pause: 5000ms
layers:
  - name: fps-showcase
    z_index: 1
    sprites:
      - type: text
        content: "FPS CAP SHOWCASE  3D"
        at: ct
        y: 1
        font: "generic:1"
        fg: white
      - type: text
        content: "SCENE 5/6  MONKEY  TARGET 20 FPS  5s"
        at: cb
        y: -1
        font: "generic:1"
        fg: gray
objects:
  - use: suzan
    id: suzanne-20
    with:
      id: suzanne-20
next: playground-fps-showcase-10
