# yaml-language-server: $schema=../../../schemas/scene.schema.yaml
id: playground-fps-showcase-10
title: FPS Showcase 3D 10
cutscene: true
target-fps: 10
bg: black
rendered-mode: quadblock
stages:
  on_idle:
    trigger: timeout
    steps:
      - pause: 5000ms
layers:
  - name: fps-showcase
    z_index: 0
    sprites:
      - type: text
        content: "FPS CAP SHOWCASE  3D"
        at: ct
        y: 1
        font: "generic:1"
        fg: white
      - type: text
        content: "SCENE 6/6  MONKEY  TARGET 10 FPS  5s"
        at: cb
        y: -1
        font: "generic:1"
        fg: gray
objects:
  - use: suzan
    id: suzanne-10
    with:
      id: suzanne-10
next: playground-menu
