pub mod camera_basis;
pub mod frame_schedule;
pub mod lighting;
pub mod object_motion;
pub mod object_specs;
pub mod runtime_builder;
pub mod runtime_store;
pub mod scene_sources;
pub mod tween_eval;
pub mod work_items;

pub use engine_3d::scene3d_atlas::{with_atlas, Scene3DAtlas};
pub use camera_basis::look_at_basis;
pub use frame_schedule::{clip_progress_at, expand_frame_samples, FrameSample};
pub use lighting::{extract_light_params, parse_hex_color, LightParams};
pub use object_motion::{resolve_object_frame_motion, ObjectFrameMotion};
pub use object_specs::{build_object_specs, ObjectRenderSpec};
pub use runtime_builder::build_scene3d_runtime_store;
pub use scene_sources::{collect_scene3d_sources, load_and_resolve_scene3d};
pub use runtime_store::{with_runtime_store, Scene3DRuntimeEntry, Scene3DRuntimeStore};
pub use tween_eval::{evaluate_tween_values, resolve_camera_frame_state, CameraFrameState, TweenValues};
pub use work_items::{build_work_items, Scene3DWorkItem};
