use crate::scene::{MeshInstance, Node3DInstance, Renderable3D};
use engine_core::render_types::Transform3D;
use engine_core::scene::{
    CameraSource, HorizontalAlign, Sprite, SpriteSizePreset, TermColour, VerticalAlign,
};

pub struct ObjSpriteSpec<'a> {
    pub sprite: &'a Sprite,
    pub node: Node3DInstance,
    pub id: Option<&'a str>,
    pub source: &'a str,
    pub size: Option<SpriteSizePreset>,
    pub width: Option<u16>,
    pub height: Option<u16>,
    pub surface_mode: Option<&'a str>,
    pub backface_cull: Option<bool>,
    pub clip_y_min: Option<f32>,
    pub clip_y_max: Option<f32>,
    pub scale: Option<f32>,
    pub yaw_deg: Option<f32>,
    pub pitch_deg: Option<f32>,
    pub roll_deg: Option<f32>,
    pub rotation_x: Option<f32>,
    pub rotation_y: Option<f32>,
    pub rotation_z: Option<f32>,
    pub rotate_y_deg_per_sec: Option<f32>,
    pub camera_distance: Option<f32>,
    pub camera_source: CameraSource,
    pub fov_degrees: Option<f32>,
    pub near_clip: Option<f32>,
    pub light_direction_x: Option<f32>,
    pub light_direction_y: Option<f32>,
    pub light_direction_z: Option<f32>,
    pub light_2_direction_x: Option<f32>,
    pub light_2_direction_y: Option<f32>,
    pub light_2_direction_z: Option<f32>,
    pub light_2_intensity: Option<f32>,
    pub light_point_x: Option<f32>,
    pub light_point_y: Option<f32>,
    pub light_point_z: Option<f32>,
    pub light_point_intensity: Option<f32>,
    pub light_point_colour: Option<&'a TermColour>,
    pub light_point_flicker_depth: Option<f32>,
    pub light_point_flicker_hz: Option<f32>,
    pub light_point_orbit_hz: Option<f32>,
    pub light_point_snap_hz: Option<f32>,
    pub light_point_2_x: Option<f32>,
    pub light_point_2_y: Option<f32>,
    pub light_point_2_z: Option<f32>,
    pub light_point_2_intensity: Option<f32>,
    pub light_point_2_colour: Option<&'a TermColour>,
    pub light_point_2_flicker_depth: Option<f32>,
    pub light_point_2_flicker_hz: Option<f32>,
    pub light_point_2_orbit_hz: Option<f32>,
    pub light_point_2_snap_hz: Option<f32>,
    pub cel_levels: Option<u8>,
    pub shadow_colour: Option<&'a TermColour>,
    pub midtone_colour: Option<&'a TermColour>,
    pub highlight_colour: Option<&'a TermColour>,
    pub tone_mix: Option<f32>,
    pub smooth_shading: Option<bool>,
    pub ambient: Option<f32>,
    pub latitude_bands: Option<u8>,
    pub latitude_band_depth: Option<f32>,
    pub terrain_color: Option<&'a TermColour>,
    pub terrain_threshold: Option<f32>,
    pub terrain_noise_scale: Option<f32>,
    pub terrain_noise_octaves: Option<u8>,
    pub marble_depth: Option<f32>,
    pub below_threshold_transparent: bool,
    pub polar_ice_color: Option<&'a TermColour>,
    pub polar_ice_start: Option<f32>,
    pub polar_ice_end: Option<f32>,
    pub desert_color: Option<&'a TermColour>,
    pub desert_strength: Option<f32>,
    pub atmo_height: Option<f32>,
    pub atmo_density: Option<f32>,
    pub atmo_rayleigh_amount: Option<f32>,
    pub atmo_rayleigh_color: Option<&'a TermColour>,
    pub atmo_rayleigh_falloff: Option<f32>,
    pub atmo_haze_amount: Option<f32>,
    pub atmo_haze_color: Option<&'a TermColour>,
    pub atmo_haze_falloff: Option<f32>,
    pub atmo_absorption_amount: Option<f32>,
    pub atmo_absorption_color: Option<&'a TermColour>,
    pub atmo_absorption_height: Option<f32>,
    pub atmo_absorption_width: Option<f32>,
    pub atmo_forward_scatter: Option<f32>,
    pub atmo_limb_boost: Option<f32>,
    pub atmo_terminator_softness: Option<f32>,
    pub atmo_night_glow: Option<f32>,
    pub atmo_night_glow_color: Option<&'a TermColour>,
    pub night_light_color: Option<&'a TermColour>,
    pub night_light_threshold: Option<f32>,
    pub night_light_intensity: Option<f32>,
    pub draw_char: Option<&'a str>,
    pub align_x: Option<HorizontalAlign>,
    pub align_y: Option<VerticalAlign>,
    pub fg_colour: Option<&'a TermColour>,
    pub bg_colour: Option<&'a TermColour>,
    pub world_x: Option<f32>,
    pub world_y: Option<f32>,
    pub world_z: Option<f32>,
    pub cam_world_x: Option<f32>,
    pub cam_world_y: Option<f32>,
    pub cam_world_z: Option<f32>,
    pub view_right_x: Option<f32>,
    pub view_right_y: Option<f32>,
    pub view_right_z: Option<f32>,
    pub view_up_x: Option<f32>,
    pub view_up_y: Option<f32>,
    pub view_up_z: Option<f32>,
    pub view_fwd_x: Option<f32>,
    pub view_fwd_y: Option<f32>,
    pub view_fwd_z: Option<f32>,
    pub visible: bool,
}

pub fn extract_obj_sprite_spec(sprite: &Sprite) -> Option<ObjSpriteSpec<'_>> {
    let Sprite::Obj {
        id,
        source,
        x,
        y,
        scale,
        pitch_deg,
        yaw_deg,
        roll_deg,
        visible,
        size,
        width,
        height,
        surface_mode,
        backface_cull,
        clip_y_min,
        clip_y_max,
        rotation_x,
        rotation_y,
        rotation_z,
        rotate_y_deg_per_sec,
        camera_distance,
        fov_degrees,
        near_clip,
        light_direction_x,
        light_direction_y,
        light_direction_z,
        light_2_direction_x,
        light_2_direction_y,
        light_2_direction_z,
        light_2_intensity,
        light_point_x,
        light_point_y,
        light_point_z,
        light_point_intensity,
        light_point_colour,
        light_point_flicker_depth,
        light_point_flicker_hz,
        light_point_orbit_hz,
        light_point_snap_hz,
        light_point_2_x,
        light_point_2_y,
        light_point_2_z,
        light_point_2_intensity,
        light_point_2_colour,
        light_point_2_flicker_depth,
        light_point_2_flicker_hz,
        light_point_2_orbit_hz,
        light_point_2_snap_hz,
        cel_levels,
        shadow_colour,
        midtone_colour,
        highlight_colour,
        tone_mix,
        smooth_shading,
        ambient,
        latitude_bands,
        latitude_band_depth,
        terrain_color,
        terrain_threshold,
        terrain_noise_scale,
        terrain_noise_octaves,
        marble_depth,
        below_threshold_transparent,
        polar_ice_color,
        polar_ice_start,
        polar_ice_end,
        desert_color,
        desert_strength,
        atmo_height,
        atmo_density,
        atmo_rayleigh_amount,
        atmo_rayleigh_color,
        atmo_rayleigh_falloff,
        atmo_haze_amount,
        atmo_haze_color,
        atmo_haze_falloff,
        atmo_absorption_amount,
        atmo_absorption_color,
        atmo_absorption_height,
        atmo_absorption_width,
        atmo_forward_scatter,
        atmo_limb_boost,
        atmo_terminator_softness,
        atmo_night_glow,
        atmo_night_glow_color,
        night_light_color,
        night_light_threshold,
        night_light_intensity,
        draw_char,
        align_x,
        align_y,
        fg_colour,
        bg_colour,
        world_x,
        world_y,
        world_z,
        cam_world_x,
        cam_world_y,
        cam_world_z,
        view_right_x,
        view_right_y,
        view_right_z,
        view_up_x,
        view_up_y,
        view_up_z,
        view_fwd_x,
        view_fwd_y,
        view_fwd_z,
        camera_source,
        ..
    } = sprite
    else {
        return None;
    };

    Some(ObjSpriteSpec {
        sprite,
        node: Node3DInstance {
            id: id.clone().unwrap_or_else(|| "obj-node".to_string()),
            transform: Transform3D {
                translation: [*x as f32, *y as f32, 0.0],
                rotation_deg: [
                    pitch_deg.unwrap_or(0.0),
                    yaw_deg.unwrap_or(0.0),
                    roll_deg.unwrap_or(0.0),
                ],
                scale: [
                    scale.unwrap_or(1.0),
                    scale.unwrap_or(1.0),
                    scale.unwrap_or(1.0),
                ],
            },
            visible: *visible,
            renderable: Renderable3D::Mesh(MeshInstance {
                source: source.clone(),
                material: None,
            }),
        },
        id: id.as_deref(),
        source,
        size: *size,
        width: *width,
        height: *height,
        surface_mode: surface_mode.as_deref(),
        backface_cull: *backface_cull,
        clip_y_min: *clip_y_min,
        clip_y_max: *clip_y_max,
        scale: *scale,
        yaw_deg: *yaw_deg,
        pitch_deg: *pitch_deg,
        roll_deg: *roll_deg,
        rotation_x: *rotation_x,
        rotation_y: *rotation_y,
        rotation_z: *rotation_z,
        rotate_y_deg_per_sec: *rotate_y_deg_per_sec,
        camera_distance: *camera_distance,
        camera_source: *camera_source,
        fov_degrees: *fov_degrees,
        near_clip: *near_clip,
        light_direction_x: *light_direction_x,
        light_direction_y: *light_direction_y,
        light_direction_z: *light_direction_z,
        light_2_direction_x: *light_2_direction_x,
        light_2_direction_y: *light_2_direction_y,
        light_2_direction_z: *light_2_direction_z,
        light_2_intensity: *light_2_intensity,
        light_point_x: *light_point_x,
        light_point_y: *light_point_y,
        light_point_z: *light_point_z,
        light_point_intensity: *light_point_intensity,
        light_point_colour: light_point_colour.as_ref(),
        light_point_flicker_depth: *light_point_flicker_depth,
        light_point_flicker_hz: *light_point_flicker_hz,
        light_point_orbit_hz: *light_point_orbit_hz,
        light_point_snap_hz: *light_point_snap_hz,
        light_point_2_x: *light_point_2_x,
        light_point_2_y: *light_point_2_y,
        light_point_2_z: *light_point_2_z,
        light_point_2_intensity: *light_point_2_intensity,
        light_point_2_colour: light_point_2_colour.as_ref(),
        light_point_2_flicker_depth: *light_point_2_flicker_depth,
        light_point_2_flicker_hz: *light_point_2_flicker_hz,
        light_point_2_orbit_hz: *light_point_2_orbit_hz,
        light_point_2_snap_hz: *light_point_2_snap_hz,
        cel_levels: *cel_levels,
        shadow_colour: shadow_colour.as_ref(),
        midtone_colour: midtone_colour.as_ref(),
        highlight_colour: highlight_colour.as_ref(),
        tone_mix: *tone_mix,
        smooth_shading: *smooth_shading,
        ambient: *ambient,
        latitude_bands: *latitude_bands,
        latitude_band_depth: *latitude_band_depth,
        terrain_color: terrain_color.as_ref(),
        terrain_threshold: *terrain_threshold,
        terrain_noise_scale: *terrain_noise_scale,
        terrain_noise_octaves: *terrain_noise_octaves,
        marble_depth: *marble_depth,
        below_threshold_transparent: *below_threshold_transparent,
        polar_ice_color: polar_ice_color.as_ref(),
        polar_ice_start: *polar_ice_start,
        polar_ice_end: *polar_ice_end,
        desert_color: desert_color.as_ref(),
        desert_strength: *desert_strength,
        atmo_height: *atmo_height,
        atmo_density: *atmo_density,
        atmo_rayleigh_amount: *atmo_rayleigh_amount,
        atmo_rayleigh_color: atmo_rayleigh_color.as_ref(),
        atmo_rayleigh_falloff: *atmo_rayleigh_falloff,
        atmo_haze_amount: *atmo_haze_amount,
        atmo_haze_color: atmo_haze_color.as_ref(),
        atmo_haze_falloff: *atmo_haze_falloff,
        atmo_absorption_amount: *atmo_absorption_amount,
        atmo_absorption_color: atmo_absorption_color.as_ref(),
        atmo_absorption_height: *atmo_absorption_height,
        atmo_absorption_width: *atmo_absorption_width,
        atmo_forward_scatter: *atmo_forward_scatter,
        atmo_limb_boost: *atmo_limb_boost,
        atmo_terminator_softness: *atmo_terminator_softness,
        atmo_night_glow: *atmo_night_glow,
        atmo_night_glow_color: atmo_night_glow_color.as_ref(),
        night_light_color: night_light_color.as_ref(),
        night_light_threshold: *night_light_threshold,
        night_light_intensity: *night_light_intensity,
        draw_char: draw_char.as_deref(),
        align_x: align_x.clone(),
        align_y: align_y.clone(),
        fg_colour: fg_colour.as_ref(),
        bg_colour: bg_colour.as_ref(),
        world_x: *world_x,
        world_y: *world_y,
        world_z: *world_z,
        cam_world_x: *cam_world_x,
        cam_world_y: *cam_world_y,
        cam_world_z: *cam_world_z,
        view_right_x: *view_right_x,
        view_right_y: *view_right_y,
        view_right_z: *view_right_z,
        view_up_x: *view_up_x,
        view_up_y: *view_up_y,
        view_up_z: *view_up_z,
        view_fwd_x: *view_fwd_x,
        view_fwd_y: *view_fwd_y,
        view_fwd_z: *view_fwd_z,
        visible: *visible,
    })
}

#[cfg(test)]
mod tests {
    use super::extract_obj_sprite_spec;
    use crate::scene::Renderable3D;
    use engine_core::scene::Sprite;

    #[test]
    fn extracts_obj_sprite_spec() {
        let sprite: Sprite = serde_yaml::from_str(
            r#"
type: obj
id: test-obj
source: /assets/3d/sphere.obj
scale: 2.0
yaw-deg: 15
surface-mode: wireframe
draw-char: "@"
"#,
        )
        .expect("obj sprite should parse");

        let spec = extract_obj_sprite_spec(&sprite).expect("spec");
        assert_eq!(spec.id, Some("test-obj"));
        assert_eq!(spec.source, "/assets/3d/sphere.obj");
        assert_eq!(spec.scale, Some(2.0));
        assert_eq!(spec.yaw_deg, Some(15.0));
        assert_eq!(spec.surface_mode, Some("wireframe"));
        assert_eq!(spec.draw_char, Some("@"));
        match &spec.node.renderable {
            Renderable3D::Mesh(mesh) => assert_eq!(mesh.source, "/assets/3d/sphere.obj"),
            _ => panic!("expected mesh renderable"),
        }
    }
}
