id: asteroids-game
title: Asteroids Game
bg: "#060620"
objects:
  - { ref: ship }
  - { ref: bullet }
  - { ref: shrapnel }
  - { ref: asteroid-large }
  - { ref: asteroid-medium }
  - { ref: asteroid-small }
  - { ref: debris }
layers:
  - ref: game/layers/hud-grid.yml
logic:
  kind: script
  behavior: rhai-script
  src: ./game-loop.rhai
stages:
  on_enter:
    steps:
      - { duration: 1 }
  on_idle:
    looping: true
    steps:
      - pause: 16ms
