id: asteroids-highscores
title: High Scores
bg: "#060620"
layers:
  - ref: highscores/layers/main-grid.yml

logic:
  kind: script
  behavior: rhai-script
  src: ./display.rhai

stages:
  on_enter:
    steps:
      - { effects: [{ name: fade-in, duration: 500 }] }
  on_idle:
    trigger: any-key
    looping: true
    steps:
      - pause: 60ms
  on_leave:
    steps:
      - { effects: [{ name: fade-out, duration: 250 }] }
