# yaml-language-server: $schema=../../../../../schemas/scene.schema.yaml
id: intro
title: Intro
cutscene: true
bg_colour: black
stages:
  on_enter:
    steps:
      - duration: 3000
        effects: []
      - effects:
          - name: crt-on
            duration: 1200
            params:
              easing: ease-out
  on_idle:
    trigger: any-key
    looping: true
    steps:
      - duration: 1800
        effects: []
      - effects:
          - name: shine
            duration: 1000
            params:
              angle: 20
              width: 4
              falloff: 2.5
              intensity: 2.0
              colour: white
              easing: ease-in
  on_leave:
    steps:
      - duration: 500
        effects: []
      - duration: 500
        effects: []
      - effects:
          - name: artifact-out
            duration: 1400
layers:
  - name: title
    z_index: 0
    visible: true
    sprites:
      - type: text
        id: intro-logo-ascii
        content: "SHELL QUEST I"
        align_x: center
        align_y: center
        font: "Abril Fatface:ascii"
        fg_colour: white
        appear_at_ms: 0
        disappear_at_ms: 3720
        stages:
          on_enter:
            steps:
              - effects:
                  - name: fade-in
                    duration: 3000
                    params:
                      easing: ease-in

      - type: text
        id: intro-logo-raster
        content: "SHELL QUEST I"
        align_x: center
        align_y: center
        font: "Abril Fatface"
        fg_colour: gray
        appear_at_ms: 3720
        stages:
          on_enter:
            steps: []
          on_idle:
            looping: true
            steps:
              - duration: 1800
                effects: []
              - effects:
                  - name: shine
                    duration: 1000
                    params:
                      angle: 20
                      width: 4
                      falloff: 2.5
                      intensity: 2.0
                      colour: white
                      easing: ease-in
          on_leave:
            steps:
              - effects:
                  - name: brighten
                    duration: 500
                    params:
                      intensity: 0.10
                      easing: ease-out
                  - name: shine
                    duration: 500
                    params:
                      angle: 20
                      width: 2
                      falloff: 3.0
                      intensity: 1.0
                      colour: white
                      easing: ease-in
              - effects:
                  - name: shine
                    duration: 500
                    params:
                      angle: -20
                      width: 2
                      falloff: 3.0
                      intensity: 1.0
                      colour: white
                      easing: ease-out

      - type: text
        id: press-any-key
        content: "[#808080]PRESS[/] ANY [#808080]KEY[/]"
        align_x: center
        align_y: center
        y: 12
        font: "generic:1"
        fg_colour: white
        hide_on_leave: true
        glow:
          radius: 1
        appear_at_ms: 8500
        animations:
          - name: float
            looping: true
            params:
              axis: y
              amplitude: 1
              period_ms: 2000
              easing: ease-in-out
next: mainmenu
