id: asteroids-mainmenu
title: Main Menu
bg: "#060620"
layers:
  - ref: mainmenu/layers/main-grid.yml
logic:
  kind: script
  behavior: rhai-script
  src: ./mainmenu.rhai
postfx:
  - name: crt-scan-glitch
    params:
      intensity: 0.05
      transparency: 0.08
      brightness: 1.0
      speed: 0.25
stages:
  on_enter:
    steps:
      - { effects: [{ name: fade-in, duration: 600 }] }
  on_idle:
    trigger: any-key
    looping: true
    steps:
      - pause: 60ms
  on_leave:
    steps:
      - { effects: [{ name: fade-out, duration: 250 }] }
